<?php

define("PROJECT_NOT_ARCHIVED"	,0);
define("PROJECT_ARCHIVED"		,1);
define("MILESTONE_NOT_ARCHIVED"	,0);
define("MILESTONE_ARCHIVED"		,1);
define("MILESTONE_NOT_DONE"		,0);
define("MILESTONE_DONE"			,1);